[package]
name = "tree-buf"
version = "0.3.0"
authors = ["Zac Burns <That3Percent@gmail.com>"]
edition = "2018"
description = "A prototype binary serialization protocol"
repository = "https://github.com/That3Percent/tree-buf"
readme = "README.md"
keywords = ["serialization", "protocol", "binary", "buffers"]
categories = ["compression", "parser-implementations"]
license = "MIT"

[badges]
maintenance = { status = "experimental"}

[dependencies]
extend-lifetime = "0.2.0"
tree-buf-macros = {version = "0.3.0", path="../tree-buf-macros" }