[package]
name = "tree-buf-macros"
version = "0.2.0"
authors = ["Zac Burns <That3Percent@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.11"
quote = "1.0.2"
proc-macro2 = "1.0.6"